scanner_name: "GE Discovery ST"
simset_material: 10
average_doi: 0.84
scanner_radius: 44.31
num_rings: 24
axial_fov: 15.7
z_crystal_size: 0.63
transaxial_crystal_size: 0.63
crystal_thickness: 3
energy_resolution: 16
num_aa_bins: 210
num_td_bins: 249
min_energy_window: 375
max_energy_window: 675
coincidence_window: 11.7
numberOfSubsets: 7
numberOfIterations: 32
savingInterval: 8
analytical_att_correction: 0
stir_recons_att_corr: 1
analytic_scatt_corr_factor: 0.15
stir_scatt_corr_smoothing: 0
stir_scatt_simulation: 0
analytic_randoms_corr_factor: 0.2
stir_randoms_corr_smoothing: 0
recons_type: "OSEM3D"
inter_iteration_filter: 0
subiteration_interval: 4
x_dir_filter_FWHM: 1.5
y_dir_filter_FWHM: 1.5
z_dir_filter_FWHM: 3
psf_value: 0
add_noise: 0
max_segment: 23
zoomFactor: 1.55
xyOutputSize: 128
zOutputSize: 47
zOutputVoxelSize: 3.27
